meta_title: "RemplaMatch - Le remplacement médical en toute simplicité"
meta_description: "Simplifiez-vous la vie en trouvant votre remplacement ou remplaçant en quelques clics : généralistes, kinésithérapeuthes et toute autre profession médicale."
meta_image: "logo_name.gif"
twitter_account: "@AntoineLoron" # indispensable pour les Twitter Cards
